name: "Test Features"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-base-features:
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      matrix:
        features:
          # Test base features first (no dependencies)
          - alpine-bash
          - alpine-build-base
          - alpine-git
          - alpine-jq
          - alpine-make
          - alpine-node
          - alpine-python
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install DevContainer CLI
        run: npm install -g @devcontainers/cli

      - name: Test feature '${{ matrix.features }}'
        id: test
        run: |
          echo "Testing feature: ${{ matrix.features }}"
          if [ -f "./test/${{ matrix.features }}/test.sh" ]; then
            echo "Running test for ${{ matrix.features }}..."
            # Run the basic test to ensure the feature installs correctly
            devcontainer features test \
              --project-folder . \
              --features ${{ matrix.features }} \
              --base-image alpine:latest \
              --skip-scenarios \
              --log-level debug
          else
            echo "No test script found for ${{ matrix.features }}"
            exit 1
          fi

  test-dependent-features:
    runs-on: ubuntu-latest
    continue-on-error: false
    needs: test-base-features
    strategy:
      matrix:
        features:
          # Test features with dependencies that are already published or have no dependencies
          - alpine-chromium
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install DevContainer CLI
        run: npm install -g @devcontainers/cli

      - name: Test feature '${{ matrix.features }}'
        id: test
        run: |
          echo "Testing feature: ${{ matrix.features }}"
          if [ -f "./test/${{ matrix.features }}/test.sh" ]; then
            echo "Running test for ${{ matrix.features }}..."
            # Run the basic test to ensure the feature installs correctly
            devcontainer features test \
              --project-folder . \
              --features ${{ matrix.features }} \
              --base-image alpine:latest \
              --skip-scenarios \
              --log-level debug
          else
            echo "No test script found for ${{ matrix.features }}"
            exit 1
          fi

  test-features-with-local-dependencies:
    runs-on: ubuntu-latest
    continue-on-error: false
    needs: test-base-features
    strategy:
      matrix:
        features:
          # Test features that depend on unpublished local features using install scripts directly
          - alpine-angular    # depends on alpine-node
          - alpine-dotnet     # depends on alpine-bash
          - alpine-gulp       # depends on alpine-node
          - alpine-jekyll     # depends on alpine-ruby
          - alpine-next       # depends on alpine-node
          - alpine-pip        # depends on alpine-python
          - alpine-puppeteer  # depends on alpine-node + alpine-chromium
          - alpine-ruby       # depends on alpine-build-base
          - alpine-workbox    # depends on alpine-node
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test feature '${{ matrix.features }}' with local dependencies
        id: test
        run: |
          echo "Testing feature with local dependencies: ${{ matrix.features }}"
          if [ -f "./test/${{ matrix.features }}/test.sh" ]; then
            echo "Running test script directly for ${{ matrix.features }}..."
            # Run the test script directly since dependencies aren't published
            cd "./test/${{ matrix.features }}"
            chmod +x test.sh
            ./test.sh
          else
            echo "No test script found for ${{ matrix.features }}"
            exit 1
          fi

  validate-features:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install DevContainer CLI
        run: npm install -g @devcontainers/cli
        
      - name: Validate all features
        run: |
          for feature in src/*/; do
            feature_name=$(basename "$feature")
            echo "Checking feature structure: $feature_name"
            if [ -f "$feature/devcontainer-feature.json" ]; then
              echo "✓ Found devcontainer-feature.json for $feature_name"
              # Check if JSON is valid
              if jq empty "$feature/devcontainer-feature.json" 2>/dev/null; then
                echo "✓ Valid JSON for $feature_name"
              else
                echo "✗ Invalid JSON for $feature_name"
                exit 1
              fi
            else
              echo "✗ Missing devcontainer-feature.json for $feature_name"
              exit 1
            fi
            if [ -f "$feature/install.sh" ]; then
              echo "✓ Found install.sh for $feature_name"
            else
              echo "✗ Missing install.sh for $feature_name"
              exit 1
            fi
          done

  test-scenarios:
    runs-on: ubuntu-latest
    needs: [test-base-features, test-dependent-features, test-features-with-local-dependencies, validate-features]
    strategy:
      matrix:
        scenario:
          # Only test scenarios for features without external dependencies
          - alpine-build-base
          - alpine-git
          - alpine-jq
          - alpine-make
          - alpine-node
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install DevContainer CLI
        run: npm install -g @devcontainers/cli

      - name: Test scenario '${{ matrix.scenario }}'
        run: |
          echo "Testing scenario: ${{ matrix.scenario }}"
          if [ -f "./test/${{ matrix.scenario }}/scenarios.json" ]; then
            # Run scenario tests for features that have them
            devcontainer features test \
              --project-folder . \
              --features ${{ matrix.scenario }} \
              --base-image alpine:latest \
              --skip-autogenerated \
              --log-level debug
          else
            echo "No scenarios.json found for ${{ matrix.scenario }}, skipping scenario tests"
            exit 0
          fi
