name: "Test Features"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      matrix:
        features:
          - alpine-angular
          - alpine-bash
          - alpine-build-base
          - alpine-chromium
          - alpine-dotnet
          - alpine-git
          - alpine-gulp
          - alpine-jekyll
          - alpine-jq
          - alpine-make
          - alpine-next
          - alpine-node
          - alpine-pip
          - alpine-puppeteer
          - alpine-python
          - alpine-ruby
          - alpine-workbox
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install DevContainer CLI
        run: npm install -g @devcontainers/cli

      - name: Test feature '${{ matrix.features }}'
        id: test
        run: |
          echo "Testing feature: ${{ matrix.features }}"
          if [ -f "./test/${{ matrix.features }}/test.sh" ]; then
            devcontainer features test \
              --project-folder . \
              --features ${{ matrix.features }} \
              --base-image alpine:latest \
              --log-level debug
          else
            echo "No test script found for ${{ matrix.features }}"
            exit 1
          fi

  validate-features:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install DevContainer CLI
        run: npm install -g @devcontainers/cli
        
      - name: Validate all features
        run: |
          for feature in src/*/; do
            feature_name=$(basename "$feature")
            echo "Checking feature structure: $feature_name"
            if [ -f "$feature/devcontainer-feature.json" ]; then
              echo "✓ Found devcontainer-feature.json for $feature_name"
              # Check if JSON is valid
              if jq empty "$feature/devcontainer-feature.json" 2>/dev/null; then
                echo "✓ Valid JSON for $feature_name"
              else
                echo "✗ Invalid JSON for $feature_name"
                exit 1
              fi
            else
              echo "✗ Missing devcontainer-feature.json for $feature_name"
              exit 1
            fi
            if [ -f "$feature/install.sh" ]; then
              echo "✓ Found install.sh for $feature_name"
            else
              echo "✗ Missing install.sh for $feature_name"
              exit 1
            fi
          done

  test-scenarios:
    runs-on: ubuntu-latest
    needs: [test, validate-features]
    strategy:
      matrix:
        scenario:
          - alpine-build-base
          - alpine-git
          - alpine-jekyll
          - alpine-jq
          - alpine-make
          - alpine-node
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install DevContainer CLI
        run: npm install -g @devcontainers/cli

      - name: Test scenario '${{ matrix.scenario }}'
        run: |
          echo "Testing scenario: ${{ matrix.scenario }}"
          if [ -f "./test/${{ matrix.scenario }}/scenarios.json" ]; then
            devcontainer features test \
              --project-folder . \
              --features ${{ matrix.scenario }} \
              --base-image alpine:latest \
              --log-level debug
          else
            echo "No scenarios.json found for ${{ matrix.scenario }}"
            exit 1
          fi
